In [4]:
import numpy as np

def compute_vector_length(v):
    return np.linalg.norm(v)

def compute_dot_product(v1, v2):
    return np.dot(v1, v2)

def matrix_multi_vector(matrix, vector):
    return np.dot(matrix, vector)

def matrix_multi_matrix(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

def invert_matrix(matrix):
    return np.linalg.inv(matrix)

def compute_eigenvalues_eigenvector(matrix):
    return np.linalg.eig(matrix)

def compute_cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))



In [ ]:
import cv2
import numpy as np

def get_background_image():
    return cv2.imread('Image data/GreenBackground.png')

def get_incoming_image():
    return cv2.imread('Image data/Object.png')

def get_fake_background():
    return cv2.imread('Image data/NewBackground.jpg')

def show_image(image, title='Image'):
    # Hiển thị hình ảnh sử dụng OpenCV
    cv2.imshow(title, image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

def resize_image(image, target_size):
    # Thay đổi kích thước ảnh để phù hợp với kích thước mục tiêu
    return cv2.resize(image, target_size, interpolation=cv2.INTER_AREA)

def background_subtraction():
    # Nhận diện hình nền và hình ảnh tới
    background = get_background_image()
    incoming_image = get_incoming_image()
    fake_background = get_fake_background()

    # Lấy kích thước của ảnh nền để làm kích thước mục tiêu
    target_size = (background.shape[1], background.shape[0])

    # Thay đổi kích thước ảnh tới và nền giả để phù hợp với kích thước ảnh nền
    incoming_image = resize_image(incoming_image, target_size)
    fake_background = resize_image(fake_background, target_size)

    # Tính toán ảnh chênh lệch
    difference = cv2.absdiff(incoming_image, background)

    # Tạo mặt nạ
    threshold = 15
    _, mask = cv2.threshold(difference, threshold, 255, cv2.THRESH_BINARY)

    # Tạo ảnh đầu ra
    output_image = np.where(mask == 0, fake_background, incoming_image)

    # Hiển thị ảnh đầu ra
    show_image(output_image, 'Output Image')

background_subtraction()


In [5]:
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))


23.28


In [6]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))


4


In [7]:
x = np.array([[1, 2],
              [3, 4]])

k = np.array([1, 2])

print('result \n', x.dot(k))


result 
 [ 5 11]


In [8]:
x = np.array([[-1, 2],
              [3, -4]])

k = np.array([1, 2])

print('result \n', x @ k)


result 
 [ 3 -5]


In [9]:
m = np.array([[-1, 1, 1], 
              [0, -4, 9]])
v = np.array([0, 2, 1])

result = matrix_multi_vector(m, v)
print(result)


[3 1]


In [10]:
m1 = np.array([[0, 1, 2], 
               [2, -3, 1]])
m2 = np.array([[1, -3], 
               [6, 1], 
               [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)


[[  6  -1]
 [-16 -10]]


In [11]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])
result = m1 @ m2
print(result)


[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [12]:
m1 = np.eye(2)

m1 = np.reshape(m1, (-1, 4))[0]

m2 = np.array([[1, 1, 1, 1],
               [2, 2, 2, 2],
               [3, 3, 3, 3],
               [4, 4, 4, 4]])

result = m1 @ m2

print(result)


[5. 5. 5. 5.]


In [13]:
m1 = np.array([[1, 2], 
               [3, 4]])

m1 = np.reshape(m1, (-1, 4), "F")[0]

m2 = np.array([[1, 1, 1, 1],
               [2, 2, 2, 2],
               [3, 3, 3, 3],
               [4, 4, 4, 4]])

result = m1 @ m2

print(result)


[29 29 29 29]


In [14]:
m1 = np.array([[-2, 6], 
               [8, -4]])
result = invert_matrix(m1)
print(result)


[[0.1  0.15]
 [0.2  0.05]]


In [16]:
matrix = np.array([[0.9, 0.2], 
                   [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvector(matrix)
print(eigenvectors)


[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [17]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine_similarity(x, y)
print(round(result, 3))


0.577
