In [32]:
import torch.nn


class Softmax(torch.nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        sum = torch.exp(x).sum()
        return torch.exp(x) / sum

In [33]:
def softmax_stable(data):
    max_val = torch.max(data)
    exp = torch.exp(data - max_val)
    return exp / torch.sum(exp)

In [34]:
# Examples 1
data = torch.tensor([1,2,3])
softmax = Softmax()
softmax_output = softmax(data)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [36]:
# Examples 1
softmax_output = softmax_stable(data)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [37]:
class Student:
    def __init__(self, name, yob, grade):
        self.name = name
        self.yob = yob
        self.grade = grade
    def description(self):
        return f"Student: {self.name} was born in {self.yob} and is in grade {self.grade}"

In [38]:
class Teacher:
    def __init__(self, name, yob, subject):
        self.name = name
        self.yob = yob
        self.subject = subject
    def description(self):
        return f"Teacher: {self.name} was born in {self.yob} and teaches {self.subject}"

In [39]:
class Doctor:
    def __init__(self, name, yob, specialty):
        self.name = name
        self.yob = yob
        self.specialty = specialty
    def description(self):
        return f"Doctor: {self.name} was born in {self.yob} and specializes in {self.specialty}"

In [40]:
student = Student("Alice", 2000, 12)
teacher = Teacher("Bob", 1970, "Math")
doctor = Doctor("Charlie", 1980, "Pediatrics")

In [41]:
print(student.description())
print(teacher.description())
print(doctor.description())

Student: Alice was born in 2000 and is in grade 12
Teacher: Bob was born in 1970 and teaches Math
Doctor: Charlie was born in 1980 and specializes in Pediatrics


In [63]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []
    def add_person(self, person):
        self.people.append(person)
    def description(self):
        des = f"Ward: {self.name} has {len(self.people)} people"
        for person in self.people:
            des += f"\n{person.description()}"
        return des
    def count_doctors(self):
        return sum([1 for person in self.people if isinstance(person, Doctor)])
    def count_teachers(self):
        return sum([1 for person in self.people if isinstance(person, Teacher)])
    def sort_age(self):
        self.people.sort(key=lambda x: x.yob)
    def compute_average(self):
        return sum([person.yob for person in self.people if isinstance(person, Teacher)]) / self.count_teachers()
    

In [64]:
teacher2 = Teacher ( name = " teacherB " , yob =1995 , subject = " History " )
doctor2 = Doctor ( name = " doctorB " , yob =1975 , specialty = " Cardiologists " )
ward = Ward("Ward1")
ward.add_person(student)
ward.add_person(teacher)
ward.add_person(doctor)
ward.add_person(teacher2)
ward.add_person(doctor2)
print(ward.description())

Ward: Ward1 has 5 people
Student: Alice was born in 2000 and is in grade 12
Teacher: Bob was born in 1970 and teaches Math
Doctor: Charlie was born in 1980 and specializes in Pediatrics
Teacher:  teacherB  was born in 1995 and teaches  History 
Doctor:  doctorB  was born in 1975 and specializes in  Cardiologists 


In [65]:
print(ward.count_doctors())

2


In [66]:
ward.sort_age()
print(ward.description())

Ward: Ward1 has 5 people
Teacher: Bob was born in 1970 and teaches Math
Doctor:  doctorB  was born in 1975 and specializes in  Cardiologists 
Doctor: Charlie was born in 1980 and specializes in Pediatrics
Teacher:  teacherB  was born in 1995 and teaches  History 
Student: Alice was born in 2000 and is in grade 12


In [67]:
print ( f" \ nAverage year of birth ( teachers ) : { ward . compute_average () } " )

 \ nAverage year of birth ( teachers ) : 1982.5 


In [68]:
class MyStack:
    def __init__(self, capacity):
        self.data = []
        self.capacity = capacity
    def push(self, x):
        self.data.append(x)
    def pop(self):
        return self.data.pop()
    def is_full(self):
        return len(self.data) == self.capacity
    def is_empty(self):
        return len(self.data) == 0
    def top(self):
        return self.data[-1]

In [70]:
stack = MyStack(5)

In [71]:
stack.push(1)
stack.push(2)
print(stack.is_full())

False


In [72]:
print(stack.top())

2


In [73]:
print(stack.pop())

2


In [74]:
print(stack.top())

1


In [75]:
print(stack.pop())

1


In [76]:
print(stack.is_empty())

True


In [77]:
class MyQueue:
    def __init__(self, capacity):
        self.data = []
        self.capacity = capacity
    def enqueue(self, x):
        self.data.append(x)
    def dequeue(self):
        return self.data.pop(0)
    def is_full(self):
        return len(self.data) == self.capacity
    def is_empty(self):
        return len(self.data) == 0
    def front(self):
        return self.data[0]

In [78]:
queue = MyQueue(5)
queue.enqueue(1)
queue.enqueue(2)
print(queue.is_full())

False


In [79]:
print(queue.front())

1


In [80]:
print(queue.dequeue())

1


In [81]:
print(queue.front())

2


In [82]:
print(queue.dequeue())

2


In [83]:
print(queue.is_empty())

True


In [84]:
# Trắc nghiệm

In [85]:
import torch
import torch.nn as nn

data = torch.Tensor([1,2,3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [87]:
data = torch.Tensor([5,2,4])
output = softmax_function(data)
assert round(output[-1].item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [90]:
data = torch.Tensor([1,2,300000000])
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.0
output

tensor([0., 0., 1.])

In [91]:
data = torch.Tensor([1,2,3])
output = softmax_stable ( data )
assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [93]:
stack1 = MyStack(5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


In [95]:
queue1 = MyQueue(5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
queue1.front()

1